backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "_site/img/"
public_folder: "/img/"

collections:
  - name: "home" # Used in routes, e.g., /admin/collections/blog
    label: "home" # Used in the UI
    folder: "home" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "staticPages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "staticPages" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    url: "{{ title }}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blogs" # Used in routes, e.g., /admin/collections/blog
    label: "blog" # Used in the UI
    folder: "blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "CV"
    name: "cv"
    widget: "object"
    folder: "cv_test" 
    fields:
      - label: "skills"
        name: "skills"
        widget: "object"
        fields: 
          - {label: "Segment title", name: "segmenttitle", widget: "string"}
          - {label: "skill 1 - Title", name: "skill1title", widget: "string"}
          - {label: "skill 1 - body", name: "skill1body", widget: "text"}
          - {label: "skill 2 - Title", name: "skill2title", widget: "string"}
          - {label: "skill 2 - body", name: "skill2body", widget: "text"}
          - {label: "skill 3 - Title", name: "skill3title", widget: "string"}
          - {label: "skill 3 - body", name: "skill3body", widget: "text"}
          - {label: "skill 4 - Title", name: "skill4title", widget: "string"}
          - {label: "skill 4 - body", name: "skill4body", widget: "text"}
          - {label: "skill 5 - Title", name: "skill5title", widget: "string"}
          - {label: "skill 5 - body", name: "skill5body", widget: "text"}
          - {label: "skill 6 - Title", name: "skill6title", widget: "string"}
          - {label: "skill 6 - body", name: "skill6body", widget: "text"}
    - label: "Summary"
      name: "summary"
      widget: "object"
      fields: 
        - {label: "Summary title", name: "summaryTitle", widget: "string"}
        - {label: "Summary body", name: "summaryBody", widget: "text"}


  